name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Format and push
        run: |
          # Git config
          git config --global user.email "1941012973.g.shreejoydash@gmail.com"
          git config --global user.name "1941012973"
          # Install autopep
          sudo apt-get install python-autopep8
          echo "Starting Formatter:"
          scripts=$(find . -type f -name "*.py")
          [[ -z $scripts ]] && echo "No pyfile detected" && exit 0
          while IFS= read -r script; do
              echo "The script is $script"
              old_hash=$(md5sum "$script")
              autopep8 -i "$script"
              new_hash=$(md5sum "$script")
              [[ "$old_hash" != "$new_hash" ]] && echo "Formatted: $script"
          done <<< "${scripts}"
          echo "linter job completed"
          git add .
          changed=$(git diff --numstat --cached | wc -l)
          if [[ "$changed" -eq 0 ]]; then
              echo "Nothing to push"
              exit 0
          fi
          git commit -m "Format py files"
          git push
